Hero Analytics: 'f2424abd-e0d6-4305-bcae-2caa80db8639'
Supply Chain Analytics: '1a19ec23-2ba0-450b-9935-def6ea465d1d'
BI360: 'b5151f96-3b01-4b17-bc95-cce8630832ac'
OnePortal: 'No test workspace'
Logistics Executive Cockpit: 'Deprecated'
Promo Analytics: 'Unknown'
Canada VC Targets: 'No test workspace'
LOLA: '013f60bf-52a5-4c5d-b5e5-c3ab818aa023'
LOLA Canada: '345bae8c-2d9a-4412-a0c3-493026315d3f'
BeerTech: 'c11032af-8da3-4fae-80cd-2db35d7de339'
Power BI Audits: 'No test workspace'
RADAR Insights: 'Unknown'
MACO: 'd91c052b-6525-4fe2-9373-4a9c732ba594'
MACO - Data Only: 'No test workspace'
Promo Lab: '778d9537-dd2f-470c-96c2-d9f81ca5d036'
Promo Lab - Data Only: 'Unknown'
Unified MACO: 'ff22a297-f17a-41b4-a8b0-1fe89fb5984e'