Hero_Analytics:
  test_workspace_id: 'f2424abd-e0d6-4305-bcae-2caa80db8639'
  pipeline_id: 'e1062274-6d15-495a-8167-5af72b82cc72'
Supply_Chain_Analytics:
  test_workspace_id:  '1a19ec23-2ba0-450b-9935-def6ea465d1d'
  pipeline_id: '078972bb-8855-40ac-8022-23f9ca34fbd5'
BI360:
  test_workspace_id:  'b5151f96-3b01-4b17-bc95-cce8630832ac'
  pipeline_id: 'd85e476b-169b-44cc-aed8-9520b3f0274e'
Canada_VC_Targets:
  test_workspace_id:  'c394e4f1-9a94-4fb0-8e35-bf32b28e83da'
  pipeline_id: 'a84ab52e-698a-4e51-a8de-5d13405a45b5'
LOLA:
  test_workspace_id:  '013f60bf-52a5-4c5d-b5e5-c3ab818aa023'
  pipeline_id: '5cfe531b-7e0d-4de5-ba8e-86a409548298'
LOLA_Canada:
  test_workspace_id:  '345bae8c-2d9a-4412-a0c3-493026315d3f'
  pipeline_id: '9de369d4-dced-4756-b099-121ac330a760'
BeerTech:
  test_workspace_id:  'c11032af-8da3-4fae-80cd-2db35d7de339'
  pipeline_id: '2364395c-4e0a-4762-a94e-ce4592cfa72e'
MACO:
  test_workspace_id:  'd91c052b-6525-4fe2-9373-4a9c732ba594'
  pipeline_id: 'fddfd71a-3536-4f64-891c-70479ad06706'
Promo_Lab:
  test_workspace_id:  '778d9537-dd2f-470c-96c2-d9f81ca5d036'
  pipeline_id: '4dea2135-db18-4739-8274-96273f0120f6'
Unified_MACO:
  test_workspace_id:  'ff22a297-f17a-41b4-a8b0-1fe89fb5984e'
  pipeline_id: 'eaae957c-399e-402f-aa25-99215329f334'
OnePortal:
  test_workspce_id:  'No test workspace'
  pipeline_id: 'No pipeline'
Logistics_Executive_Cockpit:
  test_workspace_id:  'Deprecated'
  pipeline_id: 'No pipeline'
Promo_Analytics:
  test_workspace_id:  'Unknown'
  pipeline_id: 'No pipeline'
RADAR_Insights:
  test_workspace_id:  'Unknown'
Power_BI_Audits:
  test_workspace_id:  'No test workspace'
MACO_-_Data_Only:
  test_workspace_id:  'No test workspace'
Promo_Lab_-_Data_Only:
  test_workspace_id:  'Unknown'