Workspace1:
  workspace_id:  'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  pipeline_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
Workspace2:
  workspace_id:  'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  pipeline_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
