name: Deploy Assets
on:
  push:
    branches:
      - master
jobs:
  Deploy-Asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install PyYAML
      - name: execute py script
        run: |
          python .github/scripts/deploy_report.py ${{ steps.files.outputs.all }}
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}