name: Deploy via pipeline to prod
on:
  push:
    branches:
      - main
jobs:
  pipeline-deploy:
    uses: nathangiusti/Power-BI-Reusable-Workflows/.github/workflows/pipeline-deploy.yml@main
    with:
      tenant_id: cef04b19-7776-4a94-b89b-375c77a8f936
      config_file: .github/config/report_deploy_config.yaml
      source_stage_order: 1
    secrets:
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }} 
