name: Reformat Power BI Assets
on: [pull_request]
jobs:
  Reformat-Power-BI-Assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout private actions
        uses: actions/checkout@v3                      
        with:
          repository: ab-inbev-labs/powerbi-actions
          ref: main
          token: ${{ secrets.CHAD_TEST }} 
          path: .github/workflows
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          separator: ","
          quotepath: true
      - name: Power BI VC Utils
        uses: ./.github/workflows/deserialize-pbix
        with:
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          separator: ","
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Reformatted files for VC